root = "."
testdata_dir = "testdata"
tmp_dir = "dist"

[build]
  args_bin = []
  bin = "./dist/main"
  cmd = "templ generate && go build -o ./dist/main ./src/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "dist", "src/static", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = ["find ./src -name '*templ.go' -type f -delete"]
  pre_cmd = ["pnpm build:css"]
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
